brew "cf-cli"
brew "gdbm"
brew "git-lfs"
brew "gradle"
brew "icu4c"
brew "mongodb"
brew "nvm"
brew "nyancat"
brew "openssl"
brew "pkg-config"
brew "vault"
brew "yarn"
brew "zsh-completions"
brew "mas" # Mac App Store CLI
brew "swiftlint"

cask "iterm2"
cask "postman"
