tap "romkatv/powerlevel10k"

brew "cf-cli"
brew "git"
brew "git-lfs"
brew "gradle"
brew "nvm"
brew "nyancat"
brew "yarn"
brew "zsh-completions"
brew "mas" # Mac App Store CLI
brew "swiftlint"
brew "google-java-format"
brew "zsh-syntax-highlighting"
brew "zsh-lovers"
brew "powerlevel10k"
brew "nvim"
brew "signal"
brew "jq"

cask "iterm2"
cask "postman"
cask "google-cloud-sdk"
cask "graphiql"
cask "visual-studio-code"
cask "homebrew/cask-fonts/font-sourcecodepro-nerd-font-mono"
cask "font-hack"
cask "macvim"
cask "iina"
cask "obsidian"
cask "devutils"
